"use client";
import Link from "next/link";
import { useWalletAddress } from "@/hooks/useWalletAddress";
import { useEffect, useState } from "react";
import { readClient, CONTRACT_ADDRESS } from "@/lib/clients";

interface FeedCheck {
  id: number;
  submitter: string;
  check_type: number;
  status: number;
  verdict: string;
  score: number;
  text?: string;
}

const VERDICT_CONFIG: Record<string, { color: string; bg: string; label: string }> = {
  PLAGIARIZED:  { color: "#dc2626", bg: "#fef2f2", label: "Plagiarized" },
  ORIGINAL:     { color: "#16a34a", bg: "#f0fdf4", label: "Original" },
  AI_GENERATED: { color: "#ea580c", bg: "#fff7ed", label: "AI Generated" },
  HUMAN:        { color: "#16a34a", bg: "#f0fdf4", label: "Human" },
  MIXED:        { color: "#ca8a04", bg: "#fefce8", label: "Mixed" },
};

export default function DashboardPage() {
  const address = useWalletAddress();
  const [totalChecks, setTotalChecks] = useState<number | null>(null);
  const [publicFeed, setPublicFeed] = useState<FeedCheck[] | null>(null);
  const [myActivity, setMyActivity] = useState<FeedCheck[] | null>(null);

  // Always load public feed + total count
  useEffect(() => {
    readClient
      .readContract({ address: CONTRACT_ADDRESS, functionName: "get_check_count", args: [] })
      .then((n) => setTotalChecks(Number(n as bigint)))
      .catch(() => {});

    readClient
      .readContract({ address: CONTRACT_ADDRESS, functionName: "get_recent_checks", args: [BigInt(10)] })
      .then((raw) => setPublicFeed(raw as unknown as FeedCheck[]))
      .catch(() => setPublicFeed([]));
  }, []);

  // Load my activity whenever wallet connects
  useEffect(() => {
    if (!address) { setMyActivity(null); return; }
    readClient
      .readContract({ address: CONTRACT_ADDRESS, functionName: "get_my_checks", args: [address] })
      .then((raw) => {
        const list = raw as unknown as FeedCheck[];
        setMyActivity(list.sort((a, b) => b.id - a.id).slice(0, 10));
      })
      .catch(() => setMyActivity([]));
  }, [address]);

  return (
    <div style={{ minHeight: "100vh", background: "#f8fafc", fontFamily: "inherit" }}>
      <main style={{ maxWidth: 960, margin: "0 auto", padding: "60px 24px 80px" }}>

        {/* ── Hero ─────────────────────────────────────────────────────────── */}
        <div style={{ textAlign: "center", marginBottom: 56 }}>
          <div style={{
            display: "inline-flex", alignItems: "center", gap: 6,
            background: "#f1f5f9", border: "1px solid rgba(0,0,0,0.07)",
            borderRadius: 100, padding: "5px 14px",
            fontSize: 11, fontWeight: 600, color: "#64748b",
            letterSpacing: "0.06em", textTransform: "uppercase",
            marginBottom: 22,
          }}>
            Powered by GenLayer · Testnet Bradbury
          </div>
          <h1 style={{
            fontSize: "clamp(32px, 5vw, 52px)", fontWeight: 800,
            color: "#0f172a", letterSpacing: "-0.03em",
            lineHeight: 1.1, margin: "0 0 16px",
          }}>
            Trustless content integrity,<br />verified on-chain
          </h1>
          <p style={{
            fontSize: 17, color: "#64748b", lineHeight: 1.7,
            maxWidth: 520, margin: "0 auto 32px",
          }}>
            Submit text. GenLayer validators reach consensus. Verdicts are stored
            permanently on-chain — no middlemen, no black boxes.
          </p>
          {totalChecks !== null && (
            <div style={{
              display: "inline-flex", alignItems: "baseline", gap: 6,
              background: "#fff", border: "1px solid rgba(0,0,0,0.08)",
              borderRadius: 12, padding: "10px 22px", fontSize: 14,
            }}>
              <span style={{ fontSize: 22, fontWeight: 800, color: "#0f172a" }}>
                {totalChecks.toLocaleString()}
              </span>
              <span style={{ color: "#64748b", fontWeight: 500 }}>checks run on-chain</span>
            </div>
          )}
        </div>

        {/* ── Feature cards ─────────────────────────────────────────────────── */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", gap: 20 }}>
          <FeatureCard
            href="/plagiarism"
            icon="⧉"
            title="Plagiarism Detection"
            description="Check if text was copied from the web. Validators search for matching sources and return a cited verdict, stored permanently on GenLayer."
            cta="Run plagiarism check"
            accent="#2563eb"
          />
          <FeatureCard
            href="/ai-detection"
            icon="◎"
            title="AI Detection"
            description="Determine whether text was written by a human or generated by AI. Consensus verdict from multiple independent GenLayer validators."
            cta="Run AI detection"
            accent="#7c3aed"
          />
        </div>

        {/* ── Activity feeds ────────────────────────────────────────────────── */}
        <div style={{
          marginTop: 60,
          display: "grid",
          gridTemplateColumns: address ? "1fr 1fr" : "1fr",
          gap: 24,
          alignItems: "start",
        }}>
          {/* Public Feed */}
          <FeedPanel
            title="Public Feed"
            subtitle="All recent on-chain verdicts"
            items={publicFeed}
            emptyMsg="No checks yet — be the first."
            showSubmitter
          />

          {/* My Activity (wallet required) */}
          {address ? (
            <FeedPanel
              title="Your Activity"
              subtitle={`${address.slice(0, 6)}…${address.slice(-4)}`}
              items={myActivity}
              emptyMsg="You haven't run any checks yet."
              showText
            />
          ) : (
            <div style={{
              background: "#fff",
              border: "1.5px dashed rgba(15,23,42,0.12)",
              borderRadius: 16,
              padding: "36px 28px",
              textAlign: "center",
            }}>
              <p style={{ fontSize: 14, fontWeight: 700, color: "#0f172a", margin: "0 0 6px" }}>
                Your Activity
              </p>
              <p style={{ fontSize: 13, color: "#94a3b8", margin: "0 0 20px", lineHeight: 1.6 }}>
                Connect your wallet to see your personal check history here.
              </p>
              <Link
                href="/plagiarism"
                style={{
                  display: "inline-block",
                  background: "#0f172a", color: "#f8fafc",
                  borderRadius: 100, padding: "9px 20px",
                  fontSize: 13, fontWeight: 700, textDecoration: "none",
                }}
              >
                Get started →
              </Link>
            </div>
          )}
        </div>

        {/* ── How it works ──────────────────────────────────────────────────── */}
        <div style={{ marginTop: 60 }}>
          <h2 style={{ fontSize: 20, fontWeight: 700, color: "#0f172a", margin: "0 0 24px", letterSpacing: "-0.02em" }}>
            How it works
          </h2>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 16 }}>
            {[
              { step: "1", title: "Submit", body: "Paste your text and confirm the transaction in your wallet. No account needed." },
              { step: "2", title: "Consensus", body: "Multiple GenLayer validators independently analyze the text and vote on a verdict." },
              { step: "3", title: "On-chain result", body: "The final verdict is written to the blockchain — verifiable, permanent, and tamper-proof." },
            ].map(({ step, title, body }) => (
              <div key={step} style={{
                background: "#fff", border: "1px solid rgba(0,0,0,0.07)",
                borderRadius: 14, padding: "20px 22px",
              }}>
                <div style={{
                  width: 28, height: 28, borderRadius: 8,
                  background: "#0f172a", color: "#f1f5f9",
                  display: "flex", alignItems: "center", justifyContent: "center",
                  fontSize: 12, fontWeight: 800, marginBottom: 12,
                }}>
                  {step}
                </div>
                <p style={{ fontSize: 14, fontWeight: 700, color: "#0f172a", margin: "0 0 6px" }}>{title}</p>
                <p style={{ fontSize: 13, color: "#64748b", lineHeight: 1.6, margin: 0 }}>{body}</p>
              </div>
            ))}
          </div>
        </div>

      </main>
    </div>
  );
}

// ── Feed panel ────────────────────────────────────────────────────────────────

function FeedPanel({
  title, subtitle, items, emptyMsg, showSubmitter = false, showText = false,
}: {
  title: string;
  subtitle: string;
  items: FeedCheck[] | null;
  emptyMsg: string;
  showSubmitter?: boolean;
  showText?: boolean;
}) {
  const isPublic = showSubmitter;

  return (
    <div style={{
      background: isPublic ? "#f1f5f9" : "#fff",
      border: `1px solid ${isPublic ? "rgba(0,0,0,0.07)" : "rgba(0,0,0,0.09)"}`,
      borderRadius: 16,
      overflow: "hidden",
    }}>
      {/* Header */}
      <div style={{
        padding: "18px 20px 14px",
        borderBottom: "1px solid rgba(0,0,0,0.06)",
        background: isPublic ? "#e8edf4" : "#f8fafc",
      }}>
        <div style={{ display: "flex", alignItems: "baseline", gap: 8 }}>
          <h2 style={{ fontSize: 14, fontWeight: 700, color: "#0f172a", margin: 0, letterSpacing: "-0.01em" }}>
            {title}
          </h2>
          <span style={{ fontSize: 11, color: "#94a3b8", fontFamily: isPublic ? "inherit" : "monospace" }}>
            {subtitle}
          </span>
        </div>
      </div>

      {/* Body */}
      <div style={{ padding: "10px 0" }}>
        {items === null && (
          <div style={{ padding: "24px 20px", textAlign: "center" }}>
            <span style={{ fontSize: 12, color: "#94a3b8" }}>Loading…</span>
          </div>
        )}
        {items !== null && items.length === 0 && (
          <div style={{ padding: "28px 20px", textAlign: "center" }}>
            <span style={{ fontSize: 13, color: "#94a3b8" }}>{emptyMsg}</span>
          </div>
        )}
        {items !== null && items.length > 0 && items.map((c) => (
          <FeedRow key={c.id} check={c} showSubmitter={showSubmitter} showText={showText} />
        ))}
      </div>
    </div>
  );
}

function FeedRow({ check, showSubmitter, showText }: {
  check: FeedCheck; showSubmitter: boolean; showText: boolean;
}) {
  const isPlag = check.check_type === 1;
  const isPending = check.status === 0;
  const vc = VERDICT_CONFIG[check.verdict] ?? { color: "#64748b", bg: "#f1f5f9", label: check.verdict || "Pending" };

  const excerpt = check.text
    ? check.text.slice(0, 80) + (check.text.length > 80 ? "…" : "")
    : null;

  return (
    <div style={{
      padding: "11px 20px",
      borderBottom: "1px solid rgba(0,0,0,0.045)",
      display: "flex", flexDirection: "column", gap: 5,
    }}>
      {/* Top row: type + verdict + score + id */}
      <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}>
        {/* Check type */}
        <span style={{
          fontSize: 10, fontWeight: 700,
          background: isPlag ? "#eff6ff" : "#f5f3ff",
          color: isPlag ? "#2563eb" : "#7c3aed",
          border: `1px solid ${isPlag ? "#bfdbfe" : "#ddd6fe"}`,
          borderRadius: 100, padding: "2px 8px",
          textTransform: "uppercase", letterSpacing: "0.05em",
          flexShrink: 0,
        }}>
          {isPlag ? "Plag" : "AI"}
        </span>

        {/* Verdict */}
        {isPending ? (
          <span style={{ fontSize: 11, fontWeight: 600, color: "#92400e" }}>Pending…</span>
        ) : (
          <span style={{
            fontSize: 11, fontWeight: 700,
            background: vc.bg, color: vc.color,
            borderRadius: 100, padding: "2px 9px",
            border: `1px solid ${vc.color}33`,
          }}>
            {vc.label}
          </span>
        )}

        {/* Score */}
        {!isPending && (
          <span style={{ fontSize: 11, color: "#94a3b8" }}>{check.score}%</span>
        )}

        {/* Spacer */}
        <span style={{ flex: 1 }} />

        {/* Check ID */}
        <span style={{ fontSize: 10, color: "#cbd5e1", fontFamily: "monospace", flexShrink: 0 }}>
          #{check.id}
        </span>
      </div>

      {/* Submitter (public feed) */}
      {showSubmitter && check.submitter && (
        <span style={{ fontSize: 10, color: "#94a3b8", fontFamily: "monospace" }}>
          {check.submitter.slice(0, 8)}…{check.submitter.slice(-4)}
        </span>
      )}

      {/* Text excerpt (my activity) */}
      {showText && excerpt && (
        <span style={{ fontSize: 11, color: "#64748b", lineHeight: 1.5 }}>
          {excerpt}
        </span>
      )}
    </div>
  );
}

// ── Feature card ──────────────────────────────────────────────────────────────

function FeatureCard({ href, icon, title, description, cta, accent }: {
  href: string; icon: string; title: string;
  description: string; cta: string; accent: string;
}) {
  return (
    <div style={{
      background: "#fff",
      border: "1px solid rgba(0,0,0,0.08)",
      borderRadius: 18,
      padding: "28px 28px 24px",
      display: "flex", flexDirection: "column",
    }}>
      <div style={{
        width: 42, height: 42, borderRadius: 12,
        background: accent + "12",
        border: `1px solid ${accent}22`,
        display: "flex", alignItems: "center", justifyContent: "center",
        fontSize: 20, marginBottom: 18,
      }}>
        {icon}
      </div>
      <h2 style={{ fontSize: 17, fontWeight: 700, color: "#0f172a", margin: "0 0 10px", letterSpacing: "-0.02em" }}>
        {title}
      </h2>
      <p style={{ fontSize: 13, color: "#64748b", lineHeight: 1.7, margin: "0 0 24px", flex: 1 }}>
        {description}
      </p>
      <Link
        href={href}
        style={{
          display: "inline-flex", alignItems: "center", gap: 6,
          background: accent, color: "#fff",
          borderRadius: 100, padding: "10px 22px",
          fontSize: 13, fontWeight: 700, textDecoration: "none",
          letterSpacing: "-0.01em", alignSelf: "flex-start",
        }}
      >
        {cta} →
      </Link>
    </div>
  );
}
